import {PRESETS} from './presets.mjs?v=studio-1';

// Search starting points are credited explicitly. Every setting below feeds the
// published E/C engine; species names identify targets, not verified matches.
function trial(name,source,notes,edit){
  const p=structuredClone(PRESETS.find(p=>p.name===source));
  for(const key of ['sourceKey','sourceFrames','sourceFile'])delete p[key];
  Object.assign(p,{name,reference:'E/C parameter study',source:`E/C schedules starting from ${source}`,observation:notes,
    recipe:'All geometry is generated by local E/C recursion. The species name is a target; no prescribed silhouette is used.',
    seedHalfWidth:0,leftRightPosition:.5,leftRightIntensity:.5,rounding:true,positiveWeight:.8,negativeWeight:.8,veins:true});
  edit(p);return p;
}
function compound(p,count){
  p.compound=true;p.trajectory='base';p.variant.firstRotationFull=true;
  p.variant.contractionIntensityMin=null;p.variant.contractionPositionMin=null;
  const shoot=p.stages[0];shoot.cycles=count===3?1:2;shoot.rotation=count===3?120:64;
  shoot.positions=[.2,.5,0,.5];shoot.intensities=[.8,1,.8,1];
  shoot.stemPosition=1;shoot.firstStemIntensity=shoot.stemIntensity=1;shoot.minExpansionLength=0;shoot.minContractionLength=null;
  p.stages[1]=structuredClone(PRESETS.find(q=>q.name==='Magnolia').stages[0]);
  p.stages[1].cycles=6;p.stages[1].rotation=count===3?100:80;
  p.leafletFinish=structuredClone(PRESETS.find(q=>q.name==='Magnolia').stages[1]);
  p.recipe+=' Compound blades use the selected local shoot schedule, followed by one finishing E/C cycle from the Magnolia blade schedule.';
}
export const EXPERIMENTS=[
  trial('Eastern redbud','Magnolia','Broad-blade E/C trial. The characteristic basal heart notch is not yet reproduced.',p=>{
    p.stages[0].rotation=100;p.stages[0].positions[0]=.22;p.stages[0].expansion.intensity=1.2;
  }),
  trial('Tulip tree','Magnolia','High shoot rotation produces upper lateral growth around a recessed apex. Lobe proportions remain exploratory.',p=>{
    p.stages[0].rotation=150;p.stages[0].positions[0]=.3;
  }),
  trial('Ohio buckeye','Buttercup','The E/C scaffold supplies five shoot axes; the same blade recursion runs on each. Leaflet size follows each generated axis.',p=>compound(p,5)),
  trial('Nasturtium','Ground ivy','Rounded radial E/C trial. This boundary model does not yet reproduce an interior petiole attachment.',p=>{
    p.stages[0].rotation=35;p.stages[0].positions[0]=.55;p.positiveWeight=.35;p.negativeWeight=.35;
  }),
  trial('Arrowhead','Ground ivy','Rotating shoots backward develops the basal lobes; rational rounding softens the E/C boundary.',p=>{
    p.stages[0].rotation=120;p.stages[0].positions[0]=.3;p.positiveWeight=.45;p.negativeWeight=.45;
  }),
  trial('Wood sorrel','Buttercup','One E/C cycle establishes three equal shoot axes. Identical local E/C recipes then develop together; the shallow terminal notches and blade proportions remain exploratory.',p=>compound(p,3)),
];
