import {generate,svgFor} from './leaf.mjs?v=pole-pairs-2';

const text=(x,y,s,size=20,extra='')=>`<text x="${x}" y="${y}" text-anchor="middle" font-size="${size}" ${extra}>${s}</text>`;
const point=(r,a)=>({x:650+r*Math.cos(a*Math.PI/180),y:620+r*Math.sin(a*Math.PI/180)});
const arc=(r,a,b,dash)=>{const p=point(r,a),q=point(r,b);return `<path d="M ${p.x} ${p.y} A ${r} ${r} 0 ${Math.abs(b-a)>180?1:0} ${b>a?1:0} ${q.x} ${q.y}" fill="none" stroke="black" stroke-width="1.6" stroke-dasharray="${dash}" marker-end="url(#ontology-arrow)"/>`;};
// Independent teaching recipe: one axis, three pairs of lateral shoots,
// no secondary blade recursion and no published-study parameter schedules.
export function ontologyRecipe(fullness=1,segmentation=.65){
 const stage={cycles:3,rotation:62,minExpansionLength:0,minContractionLength:0,
  positions:[.27,.5,.29,.5,.32,.5],
  intensities:[.52,.68,.48,.68,.42,.68],
  stemPosition:1,stemIntensity:.82,firstStemIntensity:.82,
  expansion:{position:1,intensity:1},contraction:{position:1,intensity:1}};
 stage.intensities=stage.intensities.map((v,i)=>i%2?.22+.5*segmentation:v*(.5+.5*fullness));
 const params={name:'Simple branching leaf',seedHalfWidth:0,trajectory:'tip',
  leftRightPosition:.5,leftRightIntensity:.5,roundPosition:.5,bladeContinue:false,
  rounding:true,positiveWeight:1.5,negativeWeight:.65,veins:true,points:false,frontier:false,
  variant:{firstRotationFull:false,vectorMode:'axis',contractionLRIntensity:true,
   connectOrigins:true,veinFollowsRounding:false,veinAtControlPoint:false,
   contractionPositionMin:0,contractionIntensityMin:0},
  stages:[stage,{...structuredClone(stage),cycles:0}]};
 // Compensate for recursive edge shortening inside the E schedule.
 // The silhouette remains generated by the engine, with no outline reshaping.
 for(let tier=1;tier<3;tier++){
  const step=generate(params).steps[tier*2];
  const branch=step.points.find(p=>p.id.startsWith('L')&&p.g===tier*2&&p.polarity>0);
  if(branch){
   const length=Math.hypot(branch.x-branch.origin.x,branch.y-branch.origin.y);
   if(length>1e-8)stage.intensities[tier*2]*=5.2*(.5+.5*fullness)*[1,.85,.65][tier]/length;
  }
 }
 return params;
}
// Four activities after Bockemuhl, printed pp. 22–23 (both supplied PDFs,
// PDF p. 7). Circular placement and reverse mature series are interpretive.
export function activityState(progress,profile='development'){
 const phase=Math.min(3,Math.floor(progress*4)),t=progress*4-phase;
 const params=ontologyRecipe(1,.8),stage=params.stages[0];
 params.trajectory='base';
 stage.rotation=68;
 stage.positions=[.48,.5,.38,.5,.32,.5];
 stage.intensities=[.58,.78,.52,.78,.44,.78];
 let length=1,stalk=0;
 if(phase===0){
  stage.cycles=1;stage.intensities[0]=.065;length=.35+.65*t;
 }else if(phase===1){
  stage.cycles=1+Math.round(t);
  stage.intensities=stage.intensities.map((v,i)=>i%2?.58:v*(.55+.45*t));
  params.positiveWeight=.85;
  params.negativeWeight=.65;
 }else{
  stage.cycles=2;
  stage.intensities=stage.intensities.map((v,i)=>i%2?(phase===2?.55-.85*t:-.3):v);
  params.positiveWeight=phase===2?.85-.15*t:.7;
  params.variant.contractionIntensityMin=null;
  params.negativeWeight=phase===2?.65-.15*t:.5;
  if(phase===3)stalk=4*t;
 }
 if(profile==='mature'){
  // Separate organizations vary the balance of activities, rather than
  // copying a developmental frame at a larger scale.
  stage.rotation+=8*Math.sin(progress*Math.PI*2);
  stage.positions[0]+=.07*Math.cos(progress*Math.PI*2);
  stage.intensities=stage.intensities.map((v,i)=>i%2?v:v*(.85+.22*Math.cos(progress*Math.PI*2)));
  length*=.9+.15*Math.sin(progress*Math.PI*2);
 }
 const result=generate(params);
 // Shooting stops at the first E: one undivided pointed primordium.
 const raw=phase===0?result.steps[0]:result.steps.at(-1);
 // Basal elongation is a separate activity: preserve the formed blade and
 // lift it above its existing attachment, leaving the root at y=0.
 const bladeScale=phase===3?1-.45*t:1;
 const move=p=>({...p,x:p.x*bladeScale,y:p.y*length*bladeScale+(p.y>1e-6?stalk:0)});
 const step={...raw,surfaces:raw.surfaces.map(poly=>poly.map(move)),
  branches:raw.branches.map(b=>({...b,a:move(b.a),b:move(b.b)}))};
 if(phase===3){
  const attachment=raw.points.find(p=>p.id==='L.0:C');
  const top=(attachment?.y??2.2)*bladeScale+stalk;
  step.surfaces.push([{x:-.1,y:0},{x:.1,y:0},{x:.1,y:top},{x:-.1,y:top}]);
 }
 return {params,step,activity:['shooting','segmenting','spreading','stemming'][phase],length,stalk};
}
export function ontologyData(){
 const outer=Array.from({length:12},(_,i)=>{
  const angle=75-i*30,progress=((angle-90+360)%360)/360;
  return {...activityState(progress,'mature'),angle};
 });
 return {outer};
}
export function ontologySvg(){
 const {outer}=ontologyData();
 let body=`<defs><marker id="ontology-arrow" viewBox="0 0 10 8" refX="9" refY="4" markerWidth="9" markerHeight="7" orient="auto"><path d="M 0 0 L 10 4 L 0 8 Z" fill="black"/></marker></defs>`;
 body+=`<path d="M 650 620 V 175 M 650 620 V 1065 M 650 620 H 180 M 650 620 H 1120" fill="none" stroke="#aaa" stroke-width=".8" marker-end="url(#ontology-arrow)"/>`;
 // Two arrowheads per trajectory. Increasing screen angle = clockwise.
 body+=arc(252,94,270,'2 5')+arc(252,270,446,'2 5');
 body+=arc(360,86,-90,'9 6')+arc(360,-90,-266,'9 6');
 const leaf=(item,r,size,id)=>{
  const p=point(r,item.angle),points=item.step.surfaces.flat();
  const extent=Math.max(...points.map(p=>Math.abs(p.x)));
  const bottom=Math.min(...points.map(p=>p.y)),top=Math.max(...points.map(p=>p.y));
  const sizeWorld=Math.max(2*extent,top-bottom)*1.12;
  const frame={x:-sizeWorld/2,y:(bottom+top-sizeWorld)/2,size:sizeWorld};
  // White axis only: no lateral venation in these analytical silhouettes.
  const step={...item.step,branches:[{a:{x:0,y:bottom},b:{x:0,y:top},depth:0}]};
  return svgFor(step,{...item.params,veins:true,points:false,frontier:false},frame,id)
   .replace('<svg ',`<svg x="${p.x-size/2}" y="${p.y-size/2}" `)
   .replace('width="800" height="800"',`width="${size}" height="${size}"`);
 };
 // One developmental trace, using construction geometry rather than leaves.
 const traces=[
  {angle:115,kind:'point'}, {angle:155,kind:'axis'},
  {angle:220,kind:'branch'}, {angle:305,kind:'blade'}, {angle:385,kind:'stalk'}
 ];
 for(const {angle,kind} of traces){
  const p=point(252,angle);
  body+=`<g transform="translate(${p.x} ${p.y})" fill="none" stroke="black" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"><rect x="-28" y="-37" width="56" height="79" fill="white" stroke="none"/>`;
  if(kind==='point')body+='<circle r="2.5" fill="black"/>';
  else{
   body+='<path d="M 0 29 V -29"/>';
   if(kind!=='axis')body+='<path d="M 0 8 L -21 -11 M 0 8 L 21 -11 M 0 8 L -13 -23 M 0 8 L 13 -23"/>';
   if(kind==='blade'||kind==='stalk')body+='<path d="M 0 8 Q -30 4 -21 -11 Q -18 -27 0 -29 Q 18 -27 21 -11 Q 30 4 0 8 Z"/>';
   if(kind==='stalk')body+='<path d="M -1 8 V 38 H 1 V 8"/>';
  }
  body+='</g>';
 }
 outer.forEach((item,i)=>{
  body+=leaf(item,360,108,`ontology-outer-${i}`);
  const p=point(424,item.angle);body+=text(p.x,p.y+4,String(i+1),12);
 });
 // Open start and filled finish, offset across the contraction axis.
 for(const [r,start,end] of [[252,94,446],[360,86,-266]]){
  const a=point(r,start),b=point(r,end);
  body+=`<circle cx="${a.x}" cy="${a.y}" r="4" fill="white" stroke="black"/><circle cx="${b.x}" cy="${b.y}" r="3.5" fill="black"/>`;
 }
 body+=text(650,45,'EMBRYOGENESIS AND ONTOGENESIS',26);
 body+=text(650,75,'Relative predominance of formative activities',18,'font-style="italic"');
 body+=text(650,133,'EXPANSION [+]',21)+text(650,158,'INTENSITY',12);
 body+=text(650,1100,'CONTRACTION [−]',21);
 body+=text(105,614,'EXPANSION [+]',18)+text(105,638,'POLARITY',12);
 body+=text(1200,614,'CONTRACTION [−]',18);
 for(const [x,y,title,sub] of [[330,220,'SEGMENTING','Gliedern'],[970,220,'SPREADING','Spreiten'],[330,1000,'SHOOTING','Spriessen'],[970,1000,'STEMMING','Stielen']])body+=text(x,y,title,23)+text(x,y+26,sub,18,'font-style="italic"');
 body+=text(405,1142,'Embryogenesis · clockwise',18)+text(900,1142,'Ontogenesis · counter-clockwise',18);
 body+=text(405,1166,'One leaf: point → axis → articulation → blade → stalk',14,'font-style="italic"');
 body+=text(900,1166,'Twelve separate foliage leaves',14,'font-style="italic"');
 body+=text(650,1208,'Figure 6.1. Radial organization of embryogenesis and ontogenesis.',17);
 body+=text(650,1233,'Analytical forms and developmental traces after Bockemühl; not reproductions of specimens.',14);
 body+=text(650,1256,'Open circle: beginning · Filled dot: ending · Opposing directions through one formative field.',14);
 return `<svg xmlns="http://www.w3.org/2000/svg" width="1300" height="1280" viewBox="0 0 1300 1280" role="img" aria-label="Embryogenesis and ontogenesis"><rect width="1300" height="1280" fill="white"/><g fill="black" font-family="Garamond, serif">${body}</g></svg>`;
}
