import {PRESETS} from './presets.mjs?v=studio-1';
export const NEUTRAL={origin:0,spread:0,fullness:0,shoots:0,blades:0,roundness:0};
export const MACRO_FIELDS=[
  ['origin','Stalk / blade origin',-.25,.25,.005,'Shift the first branching origin along the axis.'],
  ['spread','Branch spread',-25,25,.5,'Adjust E rotation in both growth phases.'],
  ['fullness','Blade fullness',-1,1,.02,'Balance expansion and contraction across the saved schedules.'],
  ['shoots','Shoot cycles + / −',-3,3,.5,'Add or remove shoot cycles relative to this form.'],
  ['blades','Blade cycles + / −',-2,2,.5,'Add or remove local blade cycles.'],
  ['roundness','Softer margins',0,1,.02,'Soften positive and negative corners without changing growth.'],
];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
// Always derive from a fixed anchor: no accumulated slider drift, exact neutral reset.
export function varyRecipe(base,values={}) {
  const p=structuredClone(base),v={...NEUTRAL,...values};
  p.stages[0].positions[0]=clamp(p.stages[0].positions[0]+v.origin,0,1);
  p.stages.forEach((s,i)=>{
    s.rotation=clamp(s.rotation+v.spread,0,180);
    s.cycles=clamp(s.cycles+(i?v.blades:v.shoots),0,20);
    s.expansion.intensity*=Math.exp(v.fullness*.22);
    s.contraction.intensity*=Math.exp(-v.fullness*.08);
  });
  if(v.roundness>0){p.rounding=true;p.positiveWeight*=Math.exp(-2*v.roundness);p.negativeWeight*=Math.exp(-2*v.roundness);}
  return p;
}
const definitions=[
  ['Narrow blade','Magnolia',{fullness:-.75,spread:-15},'A slender continuous blade with an axial vein pattern.'],
  ['Soft oval','Magnolia',{fullness:.2,spread:4,roundness:.6},'A continuous axial blade with softened margins.'],
  ['Lobed spear','Holly',{fullness:-.45,spread:-15,roundness:.35},'A narrow axial form with repeated side lobes.'],
  ['Open lobed blade','Fig',{shoots:-1,blades:-1,roundness:.5},'Radial continuations and local divisions create an open lobed blade.'],
  ['Rounded fan','Ground ivy',{spread:5,roundness:.8,fullness:.3},'A compact radial fan with a rounded edge.'],
  ['Divided fan','Saw palmetto',{shoots:-5,fullness:-.4,roundness:.25},'Fewer radial shoots leave a visibly divided fan.'],
  ['Paired leaflets','American ash',{shoots:1,fullness:-.2,roundness:.45},'Axial continuation produces additional pairs of leaflets.'],
  ['Fine frond','Fern',{shoots:-2,blades:-1,fullness:-.25,roundness:.3},'A smaller compound frond with repeated secondary divisions.'],
];
export const VARIATIONS=definitions.map(([name,parent,changes,description])=>{
  const p=varyRecipe(PRESETS.find(p=>p.name===parent),changes);
  return {...p,name,parent,reference:'Variation study',source:`Derived from ${parent}`,observation:description,
    recipe:'Generated by the same E/C rules. Descriptive form study, not a verified species reconstruction.'};
});
// A deterministic local sweep, so neighboring candidates are comparable and reproducible.
export function neighboringVariations(base) {
  return [-.3,0,.3].flatMap(fullness=>[-8,0,8].map(spread=>({
    ...varyRecipe(base,{fullness,spread}),name:`Spread ${spread>0?'+':''}${spread} / Fullness ${fullness>0?'+':''}${fullness.toFixed(1)}`,
  })));
}
