import {PRESETS,studyParams} from './presets.mjs?v=studio-1';
import {simpleButtercupRecipe} from './blade-configurations.mjs?v=pole-pairs-2';
export const NEUTRAL={origin:0,spread:0,fullness:0,shoots:0,blades:0,roundness:0};
export const MACRO_FIELDS=[
  ['origin','Stalk / blade origin',-.25,.25,.005,'Shift the first branching origin along the axis.'],
  ['spread','Branch spread',-25,25,.5,'Adjust E rotation in both growth phases.'],
  ['fullness','Blade fullness',-1,1,.02,'Balance expansion and contraction across the saved schedules.'],
  ['shoots','Shoot cycles + / −',-3,3,.5,'Add or remove shoot cycles relative to this form.'],
  ['blades','Blade cycles + / −',-2,2,.5,'Add or remove local blade cycles.'],
  ['roundness','Softer margins',0,1,.02,'Soften positive and negative corners without changing growth.'],
];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
// Always derive from a fixed anchor: no accumulated slider drift, exact neutral reset.
export function varyRecipe(base,values={}) {
  const p=structuredClone(base),v={...NEUTRAL,...values};
  // Explicit study settings establish a new E/C recipe before ordinary offsets.
  if(v.settings)for(const [key,value] of Object.entries(v.settings))p[key]=structuredClone(value);
  p.stages[0].positions[0]=clamp(p.stages[0].positions[0]+v.origin,0,1);
  p.stages.forEach((s,i)=>{
    s.rotation=clamp(s.rotation+v.spread,0,180);
    s.cycles=clamp(s.cycles+(i?v.blades:v.shoots),0,20);
    s.expansion.intensity*=Math.exp(v.fullness*.22);
    s.contraction.intensity*=Math.exp(-v.fullness*.08);
  });
  if(v.roundness>0){p.rounding=true;p.positiveWeight*=Math.exp(-2*v.roundness);p.negativeWeight*=Math.exp(-2*v.roundness);}
  if(v.bladeStem!==undefined){p.stages[1].firstStemIntensity=v.bladeStem;p.stages[1].stemIntensity=v.bladeStem;}
  return p;
}
// Controlled neighbors of recovered recipes, rather than unverified species targets.
export const VARIATIONS=[
  ['Buttercup','Open shoots',{spread:8}],
  ['Magnolia','Elliptic blade',{spread:-6,fullness:.1,roundness:.2}],
  ['Buttercup','Longer stalk',{origin:.12}],
  ['Fig','Narrow lobes',{fullness:-.7}],
  ['Fig','Soft margins',{roundness:.7}],
  ['Magnolia','Broader blade',{spread:12,fullness:.4}],
  ['Fern','Compact branching',{spread:-12}],
  ['White oak','Soft, full blade',{fullness:.25,roundness:.5}],
].map(([name,label,offsets])=>{
  const p=varyRecipe(studyParams(PRESETS.find(p=>p.name===name)),offsets);
  for(const key of ['sourceKey','sourceFrames','scriptHash'])delete p[key];
  const labels={spread:'branch spread',origin:'first E position',fullness:'fullness control',roundness:'softer margins',bladeStem:'blade stem C strength (first and later)'};
  const changes=Object.entries(offsets).map(([key,value])=>`${labels[key]??key} ${value>0?'+':''}${value}${key==='spread'?'°':''}`).join('; ');
  return {...p,name:`${name} / ${label}`,parent:name,offsets,reference:'Parametric study',
    source:`Derived from the saved ${name} definition`,
    observation:`${label}. Same E/C engine and inherited development schedules.`,
    recipe:`Changes from ${name}: ${changes}. All other growth settings are retained.`};
});

function addStudy(name,parent,params,description){
  const settings=Object.fromEntries(['trajectory','stages','positiveWeight','negativeWeight','rounding','leftRightPosition','leftRightIntensity',...(params.apices?['apices']:[])].map(k=>[k,structuredClone(params[k])]));
  const p=varyRecipe(studyParams(PRESETS.find(p=>p.name===parent)),{settings});
  for(const key of ['sourceKey','sourceFrames','scriptHash'])delete p[key];
  VARIATIONS.push({...p,name,parent,offsets:{settings},reference:'E/C form study',source:`New settings using the ${parent} rule variant`,observation:description,recipe:description+' Every state is generated by E/C; the margin uses the original rational rounding function.'});
}
const named=name=>studyParams(PRESETS.find(p=>p.name===name));
addStudy('Ivy / soft scallops','Ground ivy',varyRecipe(named('Ground ivy'),{roundness:.35,fullness:.15}),'The recovered ivy program with a slightly fuller blade and softer, rounded scallops.');
addStudy('Maple / slender lobes','Maple',varyRecipe(named('Maple'),{roundness:.25,fullness:-.25,spread:4}),'The recovered maple branching with restrained blade expansion and lightly rounded margins.');
addStudy('Buttercup / simple pointed apex','Buttercup',simpleButtercupRecipe('terminal'),'Two shoot cycles establish a simple palmate blade; side lobes are rounded and the terminal apex stays pointed.');
{
  const p=named('Ginkgo');p.stages[0].cycles=6;p.stages[0].rotation=14;p.stages[0].contraction.intensity*=1.8;p.stages[1].cycles=0;p.positiveWeight=.7;p.negativeWeight=6;p.rounding=true;
  addStudy('Fan / scalloped sectors','Ginkgo',p,'Six radial shoot cycles open a fan of scalloped sectors with tighter sinuses.');
}
{
  const p=named('Saw palmetto');p.stages[0].cycles=5;p.stages[0].rotation=18;p.stages[0].contraction.intensity*=.98;p.stages[1].cycles=0;p.positiveWeight=7;p.negativeWeight=5;p.rounding=true;
  addStudy('Star / narrow rays','Saw palmetto',p,'Five radial shoot cycles and deep contraction create a star of narrow pointed rays.');
}
{
  const p=varyRecipe(named('Walnut'),{fullness:-.22,spread:-4,roundness:.25});
  addStudy('Walnut / fine leaflets','Walnut',p,'The recovered walnut program with narrower leaflets and softly rounded margins.');
}
{
  const p=named('American ash');p.stages[0].cycles=4;p.stages[0].rotation-=16;p.stages[1].expansion.intensity*=.55;p.positiveWeight=.8;p.negativeWeight=3;p.rounding=true;
  addStudy('Pinnate / slender tiers','American ash',p,'Four linear cycles repeat slender blades along a common axis; reduced blade E narrows the tiers.');
}
{
  const p=named('Magnolia');p.stages[0].expansion.intensity*=.48;p.stages[0].rotation=72;p.stages[1].cycles=0;p.positiveWeight=.75;p.negativeWeight=.55;p.rounding=true;
  addStudy('Spear / narrow entire blade','Magnolia',p,'Reduced linear shoot expansion and rounded margins form an elongated, largely entire blade.');
}
// A deterministic local sweep, so neighboring candidates are comparable and reproducible.
export function neighboringVariations(base) {
  return [-.3,0,.3].flatMap(fullness=>[-8,0,8].map(spread=>({
    ...varyRecipe(base,{fullness,spread}),name:`Spread ${spread>0?'+':''}${spread} / Fullness ${fullness>0?'+':''}${fullness.toFixed(1)}`,
  })));
}
