import {writeFileSync} from 'node:fs';
import {GRASSHOPPER_RECIPES} from '../data/grasshopper-recipes.mjs';
import {generateGrowth} from '../growth.mjs';
import {compactRecipe} from '../recipe.mjs';
const recipes=GRASSHOPPER_RECIPES.map(p=>{
  const depths=[0,0];
  for(const step of generateGrowth(p).steps)for(const e of step.events)depths[e.phase]=Math.max(depths[e.phase],e.g+1);
  return compactRecipe(p,depths);
});
writeFileSync(new URL('../data/leaf-recipes.mjs',import.meta.url),'// Generated by tools/compact-recipes.mjs; unused tails remain available for extended growth.\nexport const LEAF_RECIPES = '+JSON.stringify(recipes,null,2)+';\n');
console.log(`Wrote ${recipes.length} compact recipes.`);
